import border from "@/shared/assets/images/products-img/Border.jpg";
import photo1 from "@/shared/assets/images/products-img/Photo1.jpg";
import photo2 from "@/shared/assets/images/products-img/Photo2.jpg";
import photo3 from "@/shared/assets/images/products-img/Photo3.jpg";
import photo4 from "@/shared/assets/images/products-img/Photo4.jpg";
import photo5 from "@/shared/assets/images/products-img/Photo5.jpg";
import photo6 from "@/shared/assets/images/products-img/Photo6.jpg";
import photo7 from "@/shared/assets/images/products-img/Photo7.jpg";
import photo8 from "@/shared/assets/images/products-img/Photo8.jpg";

export const productData = [
  {
    _id: 1,
    title: "Краска Wallquest, Brownsone MS90102",
    price: 6000,
    img: border,
    category: "Новинки",
    inStock: true,
    popularity: 95,
    createdAt: "2025-01-15",
  },
  {
    _id: 2,
    title: "Краска Wallquest, Brownsone MS90102",
    price: 4800,
    img: photo1,
    category: "Контрактные",
    inStock: true,
    popularity: 80,
    createdAt: "2025-01-19",
  },
  {
    _id: 3,
    title: "Краска Wallquest, Brownsone MS90102",
    price: 5290,
    img: photo2,
    category: "Эксклюзивные",
    inStock: true,
    popularity: 70,
    createdAt: "2025-02-10",
  },
  {
    _id: 4,
    title: "Краска Wallquest, Brownsone MS90102",
    price: 5290,
    img: photo3,
    category: "Новинки",
    inStock: false,
    popularity: 98,
    createdAt: "2025-03-01",
  },
  {
    _id: 5,
    title: "Краска Wallquest, Brownsone MS90102",
    price: 3400,
    img: photo4,
    category: "Новинки",
    inStock: true,
    popularity: 95,
    createdAt: "2025-03-15",
  },
  {
    _id: 6,
    title: "Краска Wallquest, Brownsone MS90102",
    price: 6000,
    img: photo5,
    category: "Контрактные",
    inStock: false,
    popularity: 50,
    createdAt: "2025-04-25",
  },
  {
    _id: 7,
    title: "Краска Wallquest, Brownsone MS90102",
    price: 4800,
    img: photo6,
    category: "Эксклюзивные",
    inStock: true,
    popularity: 40,
    createdAt: "2025-04-26",
  },
  {
    _id: 8,
    title: "Краска Wallquest, Brownsone MS90102",
    price: 5290,
    img: photo6,
    category: "Новинки",
    inStock: true,
    popularity: 95,
    createdAt: "2025-05-05",
  },
  {
    _id: 9,
    title: "Краска Wallquest, Brownsone MS90102",
    price: 2800,
    img: photo7,
    category: "Распродажа",
    inStock: false,
    popularity: 95,
    createdAt: "2025-05-11",
  },
  {
    _id: 10,
    title: "Краска Wallquest, Brownsone MS90102",
    price: 3400,
    img: photo8,
    category: "Новинки",
    inStock: true,
    popularity: 90,
    createdAt: "2025-05-15",
  },
  {
    _id: 11,
    title: "Краска Wallquest, Brownsone MS90102",
    price: 6000,
    img: photo5,
    category: "Контрактные",
    inStock: false,
    popularity: 51,
    createdAt: "2025-05-29",
  },
  {
    _id: 12,
    title: "Краска Wallquest, Brownsone MS90102",
    price: 4800,
    img: photo6,
    category: "Эксклюзивные",
    inStock: true,
    popularity: 90,
    createdAt: "2025-06-15",
  },
  {
    _id: 13,
    title: "Краска Wallquest, Brownsone MS90102",
    price: 5290,
    img: photo6,
    category: "Новинки",
    inStock: false,
    popularity: 40,
    createdAt: "2025-06-23",
  },
  {
    _id: 14,
    title: "Краска Wallquest, Brownsone MS90102",
    price: 2800,
    img: photo7,
    category: "Распродажа",
    inStock: true,
    popularity: 20,
    createdAt: "2025-07-02",
  },
  {
    _id: 15,
    title: "Краска Wallquest, Brownsone MS90102",
    price: 3400,
    img: photo8,
    category: "Новинки",
    inStock: true,
    popularity: 15,
    createdAt: "2025-07-21",
  },
];